name: Update Dashboard Snapshot

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-snapshot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Refresh KPI snapshot
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      run: |
        node ci/update_snapshot.js
        
    - name: Commit snapshot (if changed)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add specs/dashboard_end_state.yaml
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 ci: refresh snapshot"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}